name: Run Tests on Pull Request to Main

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Verify NPM version
        run: |
          npm install -g npm@6  
          npm -v | grep '^6\.'
        shell: bash

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
